#!/bin/sh

echo "Running gofmt..."
gofmt -w .
if [ $? -ne 0 ]; then
  echo "gofmt failed. Please fix formatting issues."
  exit 1
fi

echo "building..."
go build -o main ./cmd/server/main.go
if [ $? -ne 0 ]; then
  echo "go build failed. Please fix build issues."
  exit 1
fi

echo "Pre-commit checks passed."
