# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CollabTed Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.5'

    - name: Generate Prisma db
      run : go run github.com/steebchen/prisma-client-go generate --schema ./prisma

    - name: Push db
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run:  go run github.com/steebchen/prisma-client-go db push --schema ./prisma

    - name: Install dependencies
      run: go mod tidy

    - name: Install golangci-lint
      run:  go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Run golangci-lint
      run: golangci-lint run ./... --timeout 5m --concurrency 4
    
    - name: Format code
      run: go fmt ./...

    - name: Build code
      run: go build -v ./...
